$(document).ready(function(){
    $("#btn").click(function(){
        $("#img1").animate({
            left:'150px',
            opacity:'1',
            height:'500px',
            width:'500px'
        },'slow')
    })
})